### ISSUE TITLE
Extra white space after entry name

### ISSUE THREAD

**Issue by RezaRahmati** [RyanMarcus/dirty-json#27]
Hi

I was using v0.7, and this was in my unit tests

```
        json: 'id: \"test\"\nlang: \"en\"\nresult {\n  source: \"agent\"\n}',
        expect: `{"id":"test","lang":"en","result": { "source":"agent"}}`
```

After upgrading to 0.8 or 0.9 this is broken and it returns below json
```
        expect: `{"id":"test","lang":"en","result ": { "source":"agent"}}`
```

There is an extra white space after `result`

**Comment by RyanMarcus** [comment]
Huh, without the starting `{`, I'm surprised any version of the parser worked on that input!

I added a few extra rules to the parser that should catch this case, and I added your input to the unit tests. :)

Should be fixed in NPM version `0.9.1`.

**Comment by RezaRahmati** [comment]
Thank you

**Comment by RezaRahmati** [comment]
@RyanMarcus I just upgraded to 0.9.2 and same issue still exists
